/* map-data.js — Country data for the interactive world map */

/* Image mappings for countries */
const COUNTRY_IMAGES = {
  turkey:   'assets/city_turkey.png',
  uae:      'assets/city_uae.png',
  egypt:    'assets/city_egypt.png',
  greece:   'assets/city_greece.png',
  italy:    'assets/city_italy.png',
  france:   'assets/city_france.png',
  germany:  'assets/city_berlin.png',
  austria:  'assets/city_vienna.png',
  spain:    'assets/city_spain.png',
  china:    'assets/city_beijing.png',
  japan:    'assets/city_japan.png',
  thailand: 'assets/city_thailand.png',
  india:    'assets/city_dubai.png',
  maldives: 'assets/city_maldives.png',
  brazil:      'assets/city_brazil.png',
  portugal:    'assets/city_portugal.png',
  montenegro:  'assets/city_montenegro.png',
  morocco:     'assets/city_morocco.png',
  southkorea:  'assets/city_southkorea.png',
  vietnam:     'assets/city_vietnam.png',
  indonesia:   'assets/city_indonesia.png',
  srilanka:    'assets/city_srilanka.png',
  usa:         'assets/city_usa.png',
  mexico:      'assets/city_mexico.png',
  australia:   'assets/city_australia.png',
};

const COUNTRY_DATA = {

  turkey: {
    name: 'Турция',
    flag: '🇹🇷',
    capital: 'Анкара',
    currency: 'Турецкая лира (₺)',
    language: 'Турецкий',
    timezone: 'UTC+3',
    climate: 'Средиземноморский / Умеренный',
    visa: 'free', // free, on-arrival, required
    visaText: 'Безвизовый въезд до 30 дней',
    bestTime: 'Апрель–Июнь, Сентябрь–Октябрь',
    heroGradient: 'linear-gradient(135deg, #C0392B 0%, #E74C3C 100%)',
    description: 'Турция — страна на стыке Европы и Азии, известная богатейшей историей, роскошными пляжами Средиземноморья и уникальными ландшафтами Каппадокии.',
    attractions: [
      { name: 'Собор Святой Софии', emoji: '🕌', city: 'Стамбул', desc: 'Величественный памятник Byzantine архитектуры' },
      { name: 'Каппадокия', emoji: '🎈', city: 'Невшехир', desc: 'Полёты на воздушных шарах над сказочными скалами' },
      { name: 'Голубая мечеть', emoji: '🏛', city: 'Стамбул', desc: 'Одна из красивейших мечетей в мире' },
      { name: 'Памуккале', emoji: '♨️', city: 'Денизли', desc: 'Белоснежные травертиновые террасы' },
      { name: 'Базар Гранд Базар', emoji: '🛍', city: 'Стамбул', desc: 'Крупнейший крытый рынок в мире' },
      { name: 'Анталья', emoji: '🏖', city: 'Анталья', desc: 'Жемчужина Средиземноморского побережья' },
    ],
    photos: [
      { label: 'Стамбул', color: '#C0392B', icon: '🕌' },
      { label: 'Каппадокия', color: '#E67E22', icon: '🎈' },
      { label: 'Памуккале', color: '#2980B9', icon: '♨️' },
    ],
    tours: [
      { name: 'Стамбул 7 ночей', meta: 'Перелёт + Hilton Istanbul Bosphorus 5★', price: 189000, nights: 7 },
      { name: 'Анталья all-inclusive', meta: 'Regnum Carya 5★, всё включено', price: 245000, nights: 10 },
      { name: 'Каппадокия тур', meta: 'Museum Hotel 5★, полёт на шаре', price: 315000, nights: 8 },
      { name: 'Бодрум пляжный', meta: 'Mandarin Oriental Bodrum 5★', price: 385000, nights: 7 },
    ]
  },

  uae: {
    name: 'ОАЭ',
    flag: '🇦🇪',
    capital: 'Абу-Даби',
    currency: 'Дирхам ОАЭ (AED)',
    language: 'Арабский, Английский',
    timezone: 'UTC+4',
    climate: 'Пустынный жаркий',
    visa: 'on-arrival',
    visaText: 'Виза по прибытии (30 дней)',
    bestTime: 'Ноябрь–Апрель',
    heroGradient: 'linear-gradient(135deg, #00C6FF 0%, #0072FF 100%)',
    description: 'ОАЭ — государство на Аравийском полуострове, известное роскошным Дубаем с небоскрёбами, золотыми пляжами и самыми большими торговыми центрами мира.',
    attractions: [
      { name: 'Бурдж-Халифа', emoji: '🏙', city: 'Дубай', desc: 'Самое высокое здание в мире (828 м)' },
      { name: 'Пальма Джумейра', emoji: '🌴', city: 'Дубай', desc: 'Искусственный архипелаг-пальма' },
      { name: 'Dubai Mall', emoji: '🛍', city: 'Дубай', desc: 'Крупнейший торговый центр в мире' },
      { name: 'Дубайский фонтан', emoji: '⛲', city: 'Дубай', desc: 'Грандиозное световое шоу фонтанов' },
      { name: 'Сафари в пустыне', emoji: '🐪', city: 'Дубай', desc: 'Ночное сафари на джипах по дюнам' },
      { name: 'Мечеть шейха Зайда', emoji: '🕌', city: 'Абу-Даби', desc: 'Одна из крупнейших мечетей мира' },
    ],
    photos: [
      { label: 'Бурдж-Халифа', color: '#0072FF', icon: '🏙' },
      { label: 'Пляжи Дубая', color: '#00C6FF', icon: '🏖' },
      { label: 'Пустыня', color: '#F39C12', icon: '🐪' },
    ],
    tours: [
      { name: 'Дубай 5 ночей', meta: 'Перелёт + JW Marriott Marquis 5★', price: 265000, nights: 5 },
      { name: 'ОАЭ люкс-тур', meta: 'Бизнес-класс + Atlantis The Palm 5★', price: 680000, nights: 7 },
      { name: 'Абу-Даби + Дубай', meta: 'Rixos Premium + Address Downtown', price: 320000, nights: 6 },
      { name: 'Дубай семейный', meta: 'Jumeirah Beach Hotel 5★, аквапарк', price: 425000, nights: 7 },
    ]
  },

  egypt: {
    name: 'Египет',
    flag: '🇪🇬',
    capital: 'Каир',
    currency: 'Египетский фунт (EGP)',
    language: 'Арабский',
    timezone: 'UTC+2',
    climate: 'Пустынный, сухой',
    visa: 'on-arrival',
    visaText: 'Виза по прибытии (30 дней)',
    bestTime: 'Октябрь–Апрель',
    heroGradient: 'linear-gradient(135deg, #F39C12 0%, #E74C3C 100%)',
    description: 'Египет — страна фараонов и пирамид. Здесь цивилизация родилась более 5000 лет назад. Красное море, Нил и Сахара делают эту страну уникальной.',
    attractions: [
      { name: 'Пирамиды Гизы', emoji: '🔺', city: 'Каир', desc: 'Одно из семи чудес Древнего мира' },
      { name: 'Сфинкс', emoji: '🗿', city: 'Гиза', desc: 'Загадочная каменная скульптура эпохи фараонов' },
      { name: 'Красное море', emoji: '🤿', city: 'Хургада/Шарм', desc: 'Лучший дайвинг в Африке и на Ближнем Востоке' },
      { name: 'Луксор', emoji: '🏛', city: 'Луксор', desc: 'Долина царей, Карнакский храм' },
      { name: 'Нил', emoji: '🛳', city: 'Асуан-Луксор', desc: 'Круиз по великой реке фараонов' },
      { name: 'Каирский музей', emoji: '🏺', city: 'Каир', desc: 'Сокровища Тутанхамона и другие артефакты' },
    ],
    photos: [
      { label: 'Пирамиды', color: '#F39C12', icon: '🔺' },
      { label: 'Хургада', color: '#2980B9', icon: '🤿' },
      { label: 'Луксор', color: '#8E44AD', icon: '🏛' },
    ],
    tours: [
      { name: 'Хургада 7 ночей', meta: 'Steigenberger Aldau 5★, всё включено', price: 155000, nights: 7 },
      { name: 'Шарм-эль-Шейх', meta: 'Rixos Sharm El Sheikh 5★, all-incl', price: 172000, nights: 7 },
      { name: 'Каир + Луксор', meta: 'Marriott Mena House + круиз по Нилу', price: 245000, nights: 8 },
      { name: 'Марса-Алам', meta: 'Jaz Samaya Resort 5★, дайвинг', price: 165000, nights: 10 },
    ]
  },

  greece: {
    name: 'Греция',
    flag: '🇬🇷',
    capital: 'Афины',
    currency: 'Евро (€)',
    language: 'Греческий',
    timezone: 'UTC+2',
    climate: 'Средиземноморский',
    visa: 'required',
    visaText: 'Требуется шенгенская виза',
    bestTime: 'Апрель–Июнь, Сентябрь–Октябрь',
    heroGradient: 'linear-gradient(135deg, #2980B9 0%, #1ABC9C 100%)',
    description: 'Греция — колыбель западной цивилизации. Острова Эгейского моря, Акрополь, оливковые рощи и голубые купола Санторини — вот настоящая Эллада.',
    attractions: [
      { name: 'Акрополь', emoji: '🏛', city: 'Афины', desc: 'Символ античной Греции и всей цивилизации' },
      { name: 'Санторини', emoji: '🌅', city: 'Санторини', desc: 'Белые домики, голубые купола и закаты' },
      { name: 'Миконос', emoji: '🏝', city: 'Миконос', desc: 'Богемный остров с роскошными пляжами' },
      { name: 'Крит', emoji: '🍇', city: 'Ираклио', desc: 'Крупнейший греческий остров с Кносским дворцом' },
      { name: 'Метеоры', emoji: '⛪', city: 'Каламбака', desc: 'Монастыри на вершинах скал' },
      { name: 'Олимпия', emoji: '🏅', city: 'Элида', desc: 'Родина Олимпийских игр' },
    ],
    photos: [
      { label: 'Санторини', color: '#2980B9', icon: '🌅' },
      { label: 'Афины', color: '#8E44AD', icon: '🏛' },
      { label: 'Миконос', color: '#1ABC9C', icon: '🏝' },
    ],
    tours: [
      { name: 'Санторини 7 ночей', meta: 'Перелёт + отель с видом на кальдеру', price: 342000, nights: 7 },
      { name: 'Афины + острова', meta: 'Перелёт, паромы, отели', price: 289000, nights: 9 },
      { name: 'Крит all-inclusive', meta: 'Перелёт + отель 5★, всё включено', price: 265000, nights: 8 },
    ]
  },

  italy: {
    name: 'Италия',
    flag: '🇮🇹',
    capital: 'Рим',
    currency: 'Евро (€)',
    language: 'Итальянский',
    timezone: 'UTC+1',
    climate: 'Средиземноморский / Умеренный',
    visa: 'required',
    visaText: 'Требуется шенгенская виза',
    bestTime: 'Апрель–Июнь, Сентябрь',
    heroGradient: 'linear-gradient(135deg, #27AE60 0%, #F39C12 100%)',
    description: 'Италия — страна искусства, моды и гастрономии. Рим, Венеция, Флоренция, Амальфи — каждый город уже сам по себе шедевр.',
    attractions: [
      { name: 'Колизей', emoji: '🏟', city: 'Рим', desc: 'Крупнейший амфитеатр Древнего мира' },
      { name: 'Венеция', emoji: '🚣', city: 'Венеция', desc: 'Город на воде с гондолами и каналами' },
      { name: 'Флоренция', emoji: '🎨', city: 'Флоренция', desc: 'Центр итальянского Ренессанса' },
      { name: 'Ватикан', emoji: '⛪', city: 'Рим', desc: 'Страна-анклав со Сикстинской капеллой' },
      { name: 'Пизанская башня', emoji: '🗼', city: 'Пиза', desc: 'Знаменитая наклонная колокольня' },
      { name: 'Побережье Амальфи', emoji: '🌊', city: 'Салерно', desc: 'Живописные скалы и бирюзовое море' },
    ],
    photos: [
      { label: 'Колизей', color: '#F39C12', icon: '🏟' },
      { label: 'Венеция', color: '#2980B9', icon: '🚣' },
      { label: 'Флоренция', color: '#27AE60', icon: '🎨' },
    ],
    tours: [
      { name: 'Рим 5 ночей', meta: 'Перелёт + отель 4★ в центре', price: 295000, nights: 5 },
      { name: 'Северная Италия', meta: 'Милан, Венеция, Флоренция', price: 385000, nights: 8 },
      { name: 'Рим + Неаполь', meta: 'Перелёт, отели, экскурсии', price: 340000, nights: 7 },
    ]
  },

  france: {
    name: 'Франция',
    flag: '🇫🇷',
    capital: 'Париж',
    currency: 'Евро (€)',
    language: 'Французский',
    timezone: 'UTC+1',
    climate: 'Умеренный морской / Средиземноморский',
    visa: 'required',
    visaText: 'Требуется шенгенская виза',
    bestTime: 'Апрель–Июнь, Сентябрь–Октябрь',
    heroGradient: 'linear-gradient(135deg, #2C3E50 0%, #3498DB 100%)',
    description: 'Франция — страна романтики, высокой моды, изысканной кухни и великого искусства. Париж с Эйфелевой башней, Лазурный берег, Версаль — всё это Франция.',
    attractions: [
      { name: 'Эйфелева башня', emoji: '🗼', city: 'Париж', desc: 'Символ Франции и всего романтизма' },
      { name: 'Лувр', emoji: '🎨', city: 'Париж', desc: 'Крупнейший художественный музей мира' },
      { name: 'Версаль', emoji: '🏰', city: 'Версаль', desc: 'Роскошный дворец и садовый комплекс' },
      { name: 'Лазурный берег', emoji: '🌊', city: 'Ницца', desc: 'Ривьера с роскошными курортами' },
      { name: 'Мон-Сен-Мишель', emoji: '⛪', city: 'Нормандия', desc: 'Средневековый монастырь на скале' },
      { name: 'Провансальские поля', emoji: '💜', city: 'Прованс', desc: 'Лавандовые поля и виноградники' },
    ],
    photos: [
      { label: 'Париж', color: '#2C3E50', icon: '🗼' },
      { label: 'Ницца', color: '#3498DB', icon: '🌊' },
      { label: 'Версаль', color: '#8E44AD', icon: '🏰' },
    ],
    tours: [
      { name: 'Париж 5 ночей', meta: 'Перелёт + отель 4★ у Эйфелевой башни', price: 380000, nights: 5 },
      { name: 'Лазурный берег', meta: 'Ницца + Канны + Монако, 7 ночей', price: 520000, nights: 7 },
      { name: 'Вся Франция', meta: 'Grand Tour: Париж–Лион–Прованс', price: 645000, nights: 10 },
    ]
  },

  germany: {
    name: 'Германия',
    flag: '🇩🇪',
    capital: 'Берлин',
    currency: 'Евро (€)',
    language: 'Немецкий',
    timezone: 'UTC+1',
    climate: 'Умеренный морской',
    visa: 'required',
    visaText: 'Требуется шенгенская виза',
    bestTime: 'Май–Июль, Сентябрь–Октябрь',
    heroGradient: 'linear-gradient(135deg, #2C3E50 0%, #E74C3C 100%)',
    description: 'Германия — страна замков, лесов и знаменитых автобанов. Берлин — один из самых интересных городов Европы, Бавария — мир сказок и пива.',
    attractions: [
      { name: 'Берлинская стена', emoji: '🏛', city: 'Берлин', desc: 'Символ холодной войны и воссоединения' },
      { name: 'Замок Нойшванштайн', emoji: '🏰', city: 'Бавария', desc: 'Сказочный замок Людвига II' },
      { name: 'Рейнская долина', emoji: '🍷', city: 'Рейн', desc: 'Виноградники и средневековые замки' },
      { name: 'Октоберфест', emoji: '🍺', city: 'Мюнхен', desc: 'Крупнейший пивной фестиваль мира' },
      { name: 'Бранденбургские ворота', emoji: '🗼', city: 'Берлин', desc: 'Триумфальные ворота — символ Берлина' },
      { name: 'Гамбургская гавань', emoji: '⚓', city: 'Гамбург', desc: 'Второй по величине порт Европы' },
    ],
    photos: [
      { label: 'Берлин', color: '#2C3E50', icon: '🏛' },
      { label: 'Нойшванштайн', color: '#3498DB', icon: '🏰' },
      { label: 'Мюнхен', color: '#E67E22', icon: '🍺' },
    ],
    tours: [
      { name: 'Берлин 5 ночей', meta: 'Перелёт + отель 4★, завтраки', price: 298000, nights: 5 },
      { name: 'Бавария', meta: 'Мюнхен + замки + Альпы', price: 365000, nights: 7 },
      { name: 'Вся Германия', meta: 'Берлин + Кёльн + Мюнхен', price: 430000, nights: 9 },
    ]
  },

  austria: {
    name: 'Австрия',
    flag: '🇦🇹',
    capital: 'Вена',
    currency: 'Евро (€)',
    language: 'Немецкий',
    timezone: 'UTC+1',
    climate: 'Умеренный горный',
    visa: 'required',
    visaText: 'Требуется шенгенская виза',
    bestTime: 'Декабрь–Март (горнолыжный), Апрель–Октябрь',
    heroGradient: 'linear-gradient(135deg, #C0392B 0%, #ECF0F1 80%)',
    description: 'Австрия — страна классической музыки, балов, горнолыжных курортов и горного шоколада. Вена — один из самых красивых и культурных городов мира.',
    attractions: [
      { name: 'Венская опера', emoji: '🎭', city: 'Вена', desc: 'Одна из лучших оперных сцен мира' },
      { name: 'Дворец Шёнбрунн', emoji: '🏰', city: 'Вена', desc: 'Летняя резиденция австрийских императоров' },
      { name: 'Зальцбург', emoji: '🎵', city: 'Зальцбург', desc: 'Родина Моцарта, средневековый город' },
      { name: 'Горнолыжный Инсбрук', emoji: '⛷', city: 'Инсбрук', desc: 'Олимпийский горнолыжный курорт' },
      { name: 'Венский лес', emoji: '🌲', city: 'Вена', desc: 'Природный заповедник у стен столицы' },
      { name: 'Халльштатт', emoji: '🏔', city: 'Зальцкаммергут', desc: 'Сказочная деревушка у горного озера' },
    ],
    photos: [
      { label: 'Вена', color: '#C0392B', icon: '🎭' },
      { label: 'Зальцбург', color: '#8E44AD', icon: '🎵' },
      { label: 'Инсбрук', color: '#2980B9', icon: '⛷' },
    ],
    tours: [
      { name: 'Вена 5 ночей', meta: 'Перелёт + отель 4★, завтраки', price: 320000, nights: 5 },
      { name: 'Зальцбург тур', meta: 'Перелёт + отель 4★, экскурсии', price: 295000, nights: 4 },
      { name: 'Горнолыжная Австрия', meta: 'Инсбрук, ски-пасс включён', price: 480000, nights: 7 },
    ]
  },

  spain: {
    name: 'Испания',
    flag: '🇪🇸',
    capital: 'Мадрид',
    currency: 'Евро (€)',
    language: 'Испанский',
    timezone: 'UTC+1',
    climate: 'Средиземноморский / Умеренный',
    visa: 'required',
    visaText: 'Требуется шенгенская виза',
    bestTime: 'Апрель–Июнь, Сентябрь–Октябрь',
    heroGradient: 'linear-gradient(135deg, #C0392B 0%, #F39C12 100%)',
    description: 'Испания — страна фламенко, корриды, пляжей и великой архитектуры. Барселона Гауди, Мадрид Прадо, пляжи Коста-Брава — здесь всё есть.',
    attractions: [
      { name: 'Саграда Фамилия', emoji: '⛪', city: 'Барселона', desc: 'Шедевр Антонио Гауди, незаконченный собор' },
      { name: 'Прадо', emoji: '🎨', city: 'Мадрид', desc: 'Один из лучших художественных музеев мира' },
      { name: 'Альгамбра', emoji: '🏰', city: 'Гранада', desc: 'Мавританский дворцовый комплекс' },
      { name: 'Коста-Брава', emoji: '🏖', city: 'Каталония', desc: 'Живописное скалистое побережье' },
      { name: 'Парк Гуэль', emoji: '🌈', city: 'Барселона', desc: 'Мозаичный парк Гауди с видом на город' },
      { name: 'Флламенко-шоу', emoji: '💃', city: 'Севилья', desc: 'Самобытный испанский танец' },
    ],
    photos: [
      { label: 'Барселона', color: '#C0392B', icon: '⛪' },
      { label: 'Мадрид', color: '#F39C12', icon: '🎨' },
      { label: 'Коста-Брава', color: '#2980B9', icon: '🏖' },
    ],
    tours: [
      { name: 'Барселона 5 ночей', meta: 'Перелёт + отель 4★, завтраки', price: 312000, nights: 5 },
      { name: 'Испания целиком', meta: 'Мадрид + Барселона + Севилья', price: 455000, nights: 9 },
      { name: 'Канарские острова', meta: 'Тенерифе, all-inclusive, 10 ночей', price: 375000, nights: 10 },
    ]
  },

  china: {
    name: 'Китай',
    flag: '🇨🇳',
    capital: 'Пекин',
    currency: 'Юань (CNY)',
    language: 'Китайский (мандаринский)',
    timezone: 'UTC+8',
    climate: 'Разнообразный: умеренный, субтропический',
    visa: 'free',
    visaText: 'Безвизовый 72/144 часа (транзит)',
    bestTime: 'Апрель–Май, Сентябрь–Октябрь',
    heroGradient: 'linear-gradient(135deg, #C0392B 0%, #F39C12 100%)',
    description: 'Китай — древнейшая цивилизация с 5000-летней историей. Великая стена, терракотовая армия, мегаполисы будущего — страна невероятных контрастов.',
    attractions: [
      { name: 'Великая Китайская стена', emoji: '🏯', city: 'Матяньюй', desc: 'Одно из семи чудес Нового света' },
      { name: 'Запретный город', emoji: '🏛', city: 'Пекин', desc: 'Дворцовый комплекс китайских императоров' },
      { name: 'Терракотовая армия', emoji: '⚔️', city: 'Сиань', desc: 'Тысячи глиняных воинов императора Цинь' },
      { name: 'Башня Шанхая', emoji: '🏙', city: 'Шанхай', desc: 'Одно из высочайших зданий мира' },
      { name: 'Пиковый трамплин', emoji: '🌄', city: 'Пекин', desc: 'Смотровая площадка над Пекином' },
      { name: 'Ли-река', emoji: '🏞', city: 'Гуйлинь', desc: 'Пейзажи как на китайской гравюре' },
    ],
    photos: [
      { label: 'Пекин', color: '#C0392B', icon: '🏯' },
      { label: 'Шанхай', color: '#2C3E50', icon: '🏙' },
      { label: 'Гуйлинь', color: '#27AE60', icon: '🏞' },
    ],
    tours: [
      { name: 'Пекин 6 ночей', meta: 'Перелёт + отель 4★, завтраки', price: 215000, nights: 6 },
      { name: 'Пекин + Шанхай', meta: 'Перелёт, ж/д, отели', price: 295000, nights: 9 },
      { name: 'Лучшее Китая', meta: 'Пекин–Сиань–Гуйлинь–Шанхай', price: 420000, nights: 12 },
    ]
  },

  japan: {
    name: 'Япония',
    flag: '🇯🇵',
    capital: 'Токио',
    currency: 'Иена (JPY)',
    language: 'Японский',
    timezone: 'UTC+9',
    climate: 'Умеренный дальневосточный',
    visa: 'required',
    visaText: 'Требуется туристическая виза',
    bestTime: 'Март–Май (сакура), Октябрь–Ноябрь',
    heroGradient: 'linear-gradient(135deg, #C0392B 0%, #F8F8F8 100%)',
    description: 'Япония — страна древних самураев и суперсовременных технологий. Цветение сакуры, суши, аниме, гора Фудзи — всё это Япония.',
    attractions: [
      { name: 'Гора Фудзи', emoji: '🗻', city: 'Сидзуока', desc: 'Священная гора и символ Японии' },
      { name: 'Токийские небоскрёбы', emoji: '🏙', city: 'Токио', desc: 'Один из самых высокотехнологичных городов' },
      { name: 'Золотой храм Кинкакудзи', emoji: '⛩', city: 'Киото', desc: 'Покрытый золотом буддийский храм' },
      { name: 'Арасияма', emoji: '🎋', city: 'Киото', desc: 'Бамбуковые рощи и старинные храмы' },
      { name: 'Хиросима', emoji: '🕊', city: 'Хиросима', desc: 'Помнить историю, чтобы не повторить' },
      { name: 'Осака — кухня', emoji: '🍣', city: 'Осака', desc: 'Гастрономическая столица Японии' },
    ],
    photos: [
      { label: 'Токио', color: '#C0392B', icon: '🏙' },
      { label: 'Гора Фудзи', color: '#2C3E50', icon: '🗻' },
      { label: 'Киото', color: '#27AE60', icon: '⛩' },
    ],
    tours: [
      { name: 'Токио 7 ночей', meta: 'Перелёт + отель 4★, завтраки', price: 378000, nights: 7 },
      { name: 'Токио + Киото', meta: 'Перелёт, синкансэн, отели', price: 485000, nights: 10 },
      { name: 'Лучшее Японии', meta: 'Токио+Киото+Осака+Фудзи', price: 598000, nights: 12 },
    ]
  },

  thailand: {
    name: 'Таиланд',
    flag: '🇹🇭',
    capital: 'Бангкок',
    currency: 'Тайский бат (THB)',
    language: 'Тайский',
    timezone: 'UTC+7',
    climate: 'Тропический муссонный',
    visa: 'free',
    visaText: 'Безвизовый въезд до 30 дней',
    bestTime: 'Ноябрь–Март',
    heroGradient: 'linear-gradient(135deg, #27AE60 0%, #F39C12 100%)',
    description: 'Таиланд — "Страна улыбок". Тропические острова, буддийские храмы, экзотическая кухня, слоны и традиционные тайские рынки.',
    attractions: [
      { name: 'Большой дворец', emoji: '🏯', city: 'Бангкок', desc: 'Грандиозный комплекс королевских резиденций' },
      { name: 'Острова Пхи-Пхи', emoji: '🏝', city: 'Краби', desc: 'Живописные острова с бирюзовой водой' },
      { name: 'Пхукет', emoji: '🌴', city: 'Пхукет', desc: 'Главный курортный остров Таиланда' },
      { name: 'Чиангмай', emoji: '🐘', city: 'Чиангмай', desc: 'Культурный сердце севера, слоновий парк' },
      { name: 'Паттайя', emoji: '🎭', city: 'Паттайя', desc: 'Развлекательный курортный город' },
      { name: 'Рынок Чатучак', emoji: '🛍', city: 'Бангкок', desc: 'Крупнейший уличный рынок в мире' },
    ],
    photos: [
      { label: 'Пхукет', color: '#27AE60', icon: '🌴' },
      { label: 'Бангкок', color: '#F39C12', icon: '🏯' },
      { label: 'Острова', color: '#2980B9', icon: '🏝' },
    ],
    tours: [
      { name: 'Пхукет 10 ночей', meta: 'Banyan Tree Phuket 5★, бассейн-вилла', price: 248000, nights: 10 },
      { name: 'Бангкок + Паттайя', meta: 'Centara Grand + Hilton Pattaya', price: 195000, nights: 8 },
      { name: 'Острова Таиланда', meta: 'Rayavadee Krabi 5★, Пхи-Пхи тур', price: 310000, nights: 10 },
      { name: 'Самуи виллы', meta: 'Four Seasons Koh Samui, private pool', price: 465000, nights: 7 },
    ]
  },

  india: {
    name: 'Индия',
    flag: '🇮🇳',
    capital: 'Нью-Дели',
    currency: 'Индийская рупия (INR)',
    language: 'Хинди, Английский',
    timezone: 'UTC+5:30',
    climate: 'Тропический / Субтропический',
    visa: 'on-arrival',
    visaText: 'е-Виза (E-Visa онлайн)',
    bestTime: 'Октябрь–Март',
    heroGradient: 'linear-gradient(135deg, #F39C12 0%, #E74C3C 100%)',
    description: 'Индия — страна цивилизаций, специй и красок. Тадж-Махал, Гоа, Раджастан, Гималаи — каждый регион — отдельная страна в стране.',
    attractions: [
      { name: 'Тадж-Махал', emoji: '🕌', city: 'Агра', desc: 'Чудо Нового света, мавзолей из белого мрамора' },
      { name: 'Гоа', emoji: '🏖', city: 'Гоа', desc: 'Тропические пляжи и свободный дух' },
      { name: 'Джайпур', emoji: '🏰', city: 'Джайпур', desc: 'Розовый город Раджастана' },
      { name: 'Керала', emoji: '🚣', city: 'Куттанад', desc: 'Рисовые поля и лагуны на лодках' },
      { name: 'Варанаси', emoji: '🙏', city: 'Варанаси', desc: 'Священный город на берегу реки Ганг' },
      { name: 'Гималаи', emoji: '🏔', city: 'Манали', desc: 'Горные треки и буддийские монастыри' },
    ],
    photos: [
      { label: 'Тадж-Махал', color: '#E74C3C', icon: '🕌' },
      { label: 'Гоа', color: '#27AE60', icon: '🏖' },
      { label: 'Джайпур', color: '#F39C12', icon: '🏰' },
    ],
    tours: [
      { name: 'Гоа 10 ночей', meta: 'Перелёт + отель 4★, завтраки', price: 198000, nights: 10 },
      { name: 'Золотой треугольник', meta: 'Дели+Агра+Джайпур, гид, отели', price: 265000, nights: 8 },
      { name: 'Керала', meta: 'Круиз на хаусботе, аюрведа', price: 280000, nights: 9 },
    ]
  },

  maldives: {
    name: 'Мальдивы',
    flag: '🇲🇻',
    capital: 'Мале',
    currency: 'Мальдивская руфия (MVR)',
    language: 'Дивехи, Английский',
    timezone: 'UTC+5',
    climate: 'Тропический сезонный',
    visa: 'free',
    visaText: 'Безвизовый въезд (30 дней)',
    bestTime: 'Декабрь–Апрель',
    heroGradient: 'linear-gradient(135deg, #00B4DB 0%, #0083B0 100%)',
    description: 'Мальдивы — рай на земле. 1200 островов, бунгало над кристальной водой, коралловые рифы и нетронутые пляжи. Место для настоящего отдыха.',
    attractions: [
      { name: 'Бунгало над водой', emoji: '🌊', city: 'Атоллы', desc: 'Роскошные виллы прямо над лагуной' },
      { name: 'Дайвинг', emoji: '🤿', city: 'Маафуши', desc: 'Лучшие коралловые рифы в мире' },
      { name: 'Кит-акулы', emoji: '🦈', city: 'Южный атолл', desc: 'Плавание с крупнейшей рыбой в мире' },
      { name: 'Закат в океане', emoji: '🌅', city: 'Везде', desc: 'Незабываемые закаты над Индийским океаном' },
      { name: 'Снорклинг', emoji: '🐠', city: 'Везде', desc: 'Экзотические рыбы и черепахи у берега' },
      { name: 'Биолюминесцентный пляж', emoji: '✨', city: 'Ваадху', desc: 'Пляж светится по ночам благодаря планктону' },
    ],
    photos: [
      { label: 'Виллы', color: '#00B4DB', icon: '🌊' },
      { label: 'Дайвинг', color: '#0083B0', icon: '🤿' },
      { label: 'Закат', color: '#F39C12', icon: '🌅' },
    ],
    tours: [
      { name: 'Мальдивы 7 ночей', meta: 'Soneva Fushi 5★, бунгало над водой', price: 550000, nights: 7 },
      { name: 'Медовый месяц', meta: 'One&Only Reethi Rah, private villa', price: 950000, nights: 7 },
      { name: 'Мальдивы эконом', meta: 'Перелёт + Maafushi гостевой дом', price: 285000, nights: 7 },
      { name: 'Подводный ресторан', meta: 'Conrad Maldives 5★, Ithaa ужин', price: 720000, nights: 5 },
    ]
  },

  brazil: {
    name: 'Бразилия',
    flag: '🇧🇷',
    capital: 'Бразилиа',
    currency: 'Бразильский реал (BRL)',
    language: 'Португальский',
    timezone: 'UTC-3',
    climate: 'Тропический, влажный',
    visa: 'required',
    visaText: 'Требуется туристическая виза',
    bestTime: 'Июнь–Сентябрь',
    heroGradient: 'linear-gradient(135deg, #27AE60 0%, #F39C12 100%)',
    description: 'Бразилия — страна карнавала, самбы, Амазонки и пляжей Ипанемы. Рио-де-Жанейро с Христом-Спасителем — один из красивейших городов Земли.',
    attractions: [
      { name: 'Статуя Христа-Спасителя', emoji: '✝️', city: 'Рио-де-Жанейро', desc: 'Символ Бразилии и чудо Нового света' },
      { name: 'Пляж Копакабана', emoji: '🏖', city: 'Рио-де-Жанейро', desc: 'Легендарный городской пляж' },
      { name: 'Амазонские джунгли', emoji: '🌿', city: 'Манаус', desc: 'Крупнейший тропический лес на Земле' },
      { name: 'Водопады Игуасу', emoji: '💦', city: 'Фос-ду-Игуасу', desc: 'Одни из крупнейших водопадов мира' },
      { name: 'Карнавал в Рио', emoji: '🎉', city: 'Рио-де-Жанейро', desc: 'Крупнейший карнавал в мире' },
      { name: 'Пантанал', emoji: '🐊', city: 'Мату-Гросу', desc: 'Крупнейшие тропические болота мира' },
    ],
    photos: [
      { label: 'Рио', color: '#27AE60', icon: '✝️' },
      { label: 'Амазония', color: '#F39C12', icon: '🌿' },
      { label: 'Игуасу', color: '#2980B9', icon: '💦' },
    ],
    tours: [
      { name: 'Рио-де-Жанейро 7 нночей', meta: 'Перелёт + отель 4★, завтраки', price: 480000, nights: 7 },
      { name: 'Бразилия экспедиция', meta: 'Рио + Амазония + Игуасу', price: 745000, nights: 12 },
      { name: 'Карнавал в Рио', meta: 'Февраль, отель 4★, трибуна', price: 680000, nights: 7 },
    ]
  },

  portugal: {
    name: 'Португалия',
    flag: '🇵🇹',
    capital: 'Лиссабон',
    currency: 'Евро (€)',
    language: 'Португальский',
    timezone: 'UTC+0',
    climate: 'Средиземноморский / Океанический',
    visa: 'required',
    visaText: 'Требуется шенгенская виза',
    bestTime: 'Апрель–Июнь, Сентябрь–Октябрь',
    heroGradient: 'linear-gradient(135deg, #006600 0%, #FF0000 100%)',
    description: 'Португалия — страна мореплавателей, портвейна и фаду. Лиссабон с его трамваями, Порту с мостами и Алгарве с золотыми скалами — настоящая жемчужина Европы.',
    attractions: [
      { name: 'Башня Белен', emoji: '🏰', city: 'Лиссабон', desc: 'Символ эпохи великих открытий' },
      { name: 'Порту', emoji: '🍷', city: 'Порту', desc: 'Город портвейна и красочных фасадов' },
      { name: 'Алгарве', emoji: '🏖', city: 'Фару', desc: 'Золотые скалы и бирюзовое море' },
      { name: 'Синтра', emoji: '🏰', city: 'Синтра', desc: 'Сказочные дворцы в горном лесу' },
      { name: 'Трамвай 28', emoji: '🚋', city: 'Лиссабон', desc: 'Легендарный жёлтый трамвай по холмам' },
      { name: 'Мадейра', emoji: '🌿', city: 'Фуншал', desc: 'Цветочный остров в Атлантике' },
    ],
    photos: [
      { label: 'Лиссабон', color: '#E74C3C', icon: '🚋' },
      { label: 'Порту', color: '#2980B9', icon: '🍷' },
      { label: 'Алгарве', color: '#F39C12', icon: '🏖' },
    ],
    tours: [
      { name: 'Лиссабон 5 ночей', meta: 'Перелёт + Hotel Avenida Palace 4★', price: 285000, nights: 5 },
      { name: 'Порту + Лиссабон', meta: 'Перелёт, поезд, отели 4★', price: 365000, nights: 7 },
      { name: 'Алгарве all-inclusive', meta: 'Pine Cliffs Resort 5★, пляж', price: 420000, nights: 8 },
    ]
  },

  montenegro: {
    name: 'Черногория',
    flag: '🇲🇪',
    capital: 'Подгорица',
    currency: 'Евро (€)',
    language: 'Черногорский',
    timezone: 'UTC+1',
    climate: 'Средиземноморский / Горный',
    visa: 'free',
    visaText: 'Безвизовый въезд до 30 дней',
    bestTime: 'Май–Сентябрь',
    heroGradient: 'linear-gradient(135deg, #C0392B 0%, #F39C12 100%)',
    description: 'Черногория — маленькая страна с потрясающей природой. Которский залив, Будва, Святой Стефан — Адриатика здесь невероятно красива.',
    attractions: [
      { name: 'Которский залив', emoji: '⛵', city: 'Котор', desc: 'Фьорд Средиземноморья, объект ЮНЕСКО' },
      { name: 'Будва', emoji: '🏖', city: 'Будва', desc: 'Главный курортный город побережья' },
      { name: 'Святой Стефан', emoji: '🏝', city: 'Будва', desc: 'Роскошный остров-отель Aman Resorts' },
      { name: 'Дурмитор', emoji: '🏔', city: 'Жабляк', desc: 'Национальный парк с горными озёрами' },
      { name: 'Старый город Котор', emoji: '🏛', city: 'Котор', desc: 'Средневековый город-крепость' },
      { name: 'Скадарское озеро', emoji: '🦅', city: 'Подгорица', desc: 'Крупнейшее озеро Балкан' },
    ],
    photos: [
      { label: 'Котор', color: '#2980B9', icon: '⛵' },
      { label: 'Будва', color: '#F39C12', icon: '🏖' },
      { label: 'Дурмитор', color: '#27AE60', icon: '🏔' },
    ],
    tours: [
      { name: 'Будва 7 ночей', meta: 'Перелёт + Hotel Splendid 5★', price: 215000, nights: 7 },
      { name: 'Котор + Будва', meta: 'Перелёт, отели 4★, экскурсии', price: 248000, nights: 8 },
      { name: 'Святой Стефан люкс', meta: 'Aman Sveti Stefan 5★, завтраки', price: 580000, nights: 5 },
    ]
  },

  morocco: {
    name: 'Марокко',
    flag: '🇲🇦',
    capital: 'Рабат',
    currency: 'Марокканский дирхам (MAD)',
    language: 'Арабский, Французский',
    timezone: 'UTC+1',
    climate: 'Средиземноморский / Пустынный',
    visa: 'free',
    visaText: 'Безвизовый въезд до 90 дней',
    bestTime: 'Март–Май, Сентябрь–Ноябрь',
    heroGradient: 'linear-gradient(135deg, #C0392B 0%, #27AE60 100%)',
    description: 'Марокко — страна контрастов на стыке Африки и Европы. Марракеш, Фес, Сахара, голубой Шефшауэн — восточная сказка наяву.',
    attractions: [
      { name: 'Медина Марракеша', emoji: '🏛', city: 'Марракеш', desc: 'Лабиринт улочек и базаров' },
      { name: 'Сахара', emoji: '🐪', city: 'Мерзуга', desc: 'Ночь под звёздами в пустыне' },
      { name: 'Шефшауэн', emoji: '💙', city: 'Шефшауэн', desc: 'Голубой город в горах Риф' },
      { name: 'Фес', emoji: '🕌', city: 'Фес', desc: 'Крупнейшая средневековая медина мира' },
      { name: 'Эс-Сувейра', emoji: '🌊', city: 'Эс-Сувейра', desc: 'Портовый город с атмосферой свободы' },
      { name: 'Атласские горы', emoji: '🏔', city: 'Атлас', desc: 'Трек через берберские деревни' },
    ],
    photos: [
      { label: 'Марракеш', color: '#C0392B', icon: '🏛' },
      { label: 'Сахара', color: '#F39C12', icon: '🐪' },
      { label: 'Шефшауэн', color: '#2980B9', icon: '💙' },
    ],
    tours: [
      { name: 'Марракеш 5 ночей', meta: 'Перелёт + Riad 4★ в медине', price: 195000, nights: 5 },
      { name: 'Имперские города', meta: 'Марракеш+Фес+Рабат, гид', price: 285000, nights: 8 },
      { name: 'Сахара экспедиция', meta: 'Джип-тур, ночь в лагере, La Mamounia 5★', price: 365000, nights: 7 },
    ]
  },

  southkorea: {
    name: 'Южная Корея',
    flag: '🇰🇷',
    capital: 'Сеул',
    currency: 'Южнокорейская вона (KRW)',
    language: 'Корейский',
    timezone: 'UTC+9',
    climate: 'Умеренный муссонный',
    visa: 'free',
    visaText: 'Безвизовый въезд до 30 дней',
    bestTime: 'Апрель–Май, Сентябрь–Ноябрь',
    heroGradient: 'linear-gradient(135deg, #2C3E50 0%, #3498DB 100%)',
    description: 'Южная Корея — страна K-pop, высоких технологий и древних храмов. Сеул — мегаполис будущего, а Чеджу — тропический рай в Восточной Азии.',
    attractions: [
      { name: 'Кёнбоккун', emoji: '🏯', city: 'Сеул', desc: 'Главный королевский дворец Кореи' },
      { name: 'Мёндон', emoji: '🛍', city: 'Сеул', desc: 'Шоппинг-район с K-beauty и модой' },
      { name: 'Остров Чеджу', emoji: '🏝', city: 'Чеджу', desc: 'Вулканический остров с пляжами' },
      { name: 'Букчон Ханок', emoji: '🏘', city: 'Сеул', desc: 'Квартал традиционных корейских домов' },
      { name: 'DMZ', emoji: '🔭', city: 'Пхаджу', desc: 'Демилитаризованная зона на границе' },
      { name: 'Пусан', emoji: '🌊', city: 'Пусан', desc: 'Портовый город с храмом Хэдонъён' },
    ],
    photos: [
      { label: 'Сеул', color: '#2C3E50', icon: '🏯' },
      { label: 'Чеджу', color: '#27AE60', icon: '🏝' },
      { label: 'Пусан', color: '#2980B9', icon: '🌊' },
    ],
    tours: [
      { name: 'Сеул 6 ночей', meta: 'Перелёт + Lotte Hotel 5★, завтраки', price: 298000, nights: 6 },
      { name: 'Сеул + Чеджу', meta: 'Перелёт, внутр. рейс, отели 4★', price: 385000, nights: 9 },
      { name: 'K-Pop тур', meta: 'Сеул, студии, концерт, шоппинг', price: 345000, nights: 7 },
    ]
  },

  vietnam: {
    name: 'Вьетнам',
    flag: '🇻🇳',
    capital: 'Ханой',
    currency: 'Вьетнамский донг (VND)',
    language: 'Вьетнамский',
    timezone: 'UTC+7',
    climate: 'Тропический муссонный',
    visa: 'free',
    visaText: 'Безвизовый въезд до 15 дней',
    bestTime: 'Ноябрь–Апрель',
    heroGradient: 'linear-gradient(135deg, #C0392B 0%, #F39C12 100%)',
    description: 'Вьетнам — страна потрясающей природы, дешёвой уличной еды и тёплого моря. Бухта Халонг, рисовые террасы Сапы и пляжи Нячанга не оставят равнодушными.',
    attractions: [
      { name: 'Бухта Халонг', emoji: '🏞', city: 'Куангнинь', desc: 'Тысячи известняковых скал в море, ЮНЕСКО' },
      { name: 'Хойан', emoji: '🏮', city: 'Хойан', desc: 'Старинный город с фонариками' },
      { name: 'Нячанг', emoji: '🏖', city: 'Нячанг', desc: 'Главный пляжный курорт Вьетнама' },
      { name: 'Сапа', emoji: '🌾', city: 'Лаокай', desc: 'Рисовые террасы в горах' },
      { name: 'Фукуок', emoji: '🌴', city: 'Фукуок', desc: 'Тропический остров с белым песком' },
      { name: 'Тоннели Ку Чи', emoji: '🏛', city: 'Хошимин', desc: 'Подземные тоннели времён войны' },
    ],
    photos: [
      { label: 'Бухта Халонг', color: '#2980B9', icon: '🏞' },
      { label: 'Хойан', color: '#E74C3C', icon: '🏮' },
      { label: 'Нячанг', color: '#27AE60', icon: '🏖' },
    ],
    tours: [
      { name: 'Нячанг 10 ночей', meta: 'Перелёт + Vinpearl Resort 5★', price: 198000, nights: 10 },
      { name: 'Ханой + Халонг', meta: 'Перелёт, круиз по бухте, отель 4★', price: 235000, nights: 7 },
      { name: 'Весь Вьетнам', meta: 'Ханой–Хойан–Нячанг–Хошимин', price: 345000, nights: 12 },
    ]
  },

  indonesia: {
    name: 'Индонезия',
    flag: '🇮🇩',
    capital: 'Джакарта',
    currency: 'Индонезийская рупия (IDR)',
    language: 'Индонезийский',
    timezone: 'UTC+8',
    climate: 'Тропический экваториальный',
    visa: 'on-arrival',
    visaText: 'Виза по прибытии (30 дней)',
    bestTime: 'Апрель–Октябрь',
    heroGradient: 'linear-gradient(135deg, #C0392B 0%, #ECF0F1 100%)',
    description: 'Индонезия — крупнейший архипелаг мира. Бали с рисовыми террасами и храмами, Ломбок, Комодо — рай для путешественников.',
    attractions: [
      { name: 'Храм Улувату', emoji: '⛩', city: 'Бали', desc: 'Храм на скале с видом на океан' },
      { name: 'Рисовые террасы Тегаллаланг', emoji: '🌾', city: 'Бали', desc: 'Знаменитые ступенчатые поля' },
      { name: 'Комодо', emoji: '🦎', city: 'НТТ', desc: 'Остров драконов Комодо' },
      { name: 'Убуд', emoji: '🐒', city: 'Бали', desc: 'Лес обезьян и центр йоги' },
      { name: 'Гили острова', emoji: '🏝', city: 'Ломбок', desc: 'Три маленьких рая без машин' },
      { name: 'Вулкан Батур', emoji: '🌋', city: 'Бали', desc: 'Встретить рассвет на вулкане' },
    ],
    photos: [
      { label: 'Бали храмы', color: '#F39C12', icon: '⛩' },
      { label: 'Террасы', color: '#27AE60', icon: '🌾' },
      { label: 'Комодо', color: '#2980B9', icon: '🦎' },
    ],
    tours: [
      { name: 'Бали 10 ночей', meta: 'Перелёт + The Mulia Resort 5★', price: 285000, nights: 10 },
      { name: 'Бали + Ломбок', meta: 'Перелёт, отели 4★, Гили острова', price: 345000, nights: 12 },
      { name: 'Бали люкс виллы', meta: 'Private pool villa, завтраки', price: 495000, nights: 7 },
    ]
  },

  srilanka: {
    name: 'Шри-Ланка',
    flag: '🇱🇰',
    capital: 'Коломбо',
    currency: 'Шри-ланкийская рупия (LKR)',
    language: 'Сингальский, Тамильский',
    timezone: 'UTC+5:30',
    climate: 'Тропический муссонный',
    visa: 'on-arrival',
    visaText: 'ETA виза онлайн (30 дней)',
    bestTime: 'Декабрь–Март',
    heroGradient: 'linear-gradient(135deg, #8E44AD 0%, #F39C12 100%)',
    description: 'Шри-Ланка — «жемчужина Индийского океана». Древние храмы, чайные плантации, дикие слоны и великолепные пляжи на одном острове.',
    attractions: [
      { name: 'Сигирия', emoji: '🏛', city: 'Дамбулла', desc: 'Крепость на скале «Львиная гора»' },
      { name: 'Храм Зуба Будды', emoji: '🕌', city: 'Канди', desc: 'Главная буддийская святыня острова' },
      { name: 'Чайные плантации', emoji: '🍵', city: 'Нувара-Элия', desc: 'Холмы покрытые зелёным чаем' },
      { name: 'Унаватуна', emoji: '🏖', city: 'Галле', desc: 'Один из лучших пляжей Азии' },
      { name: 'Слоновий приют', emoji: '🐘', city: 'Пиннавела', desc: 'Приют для осиротевших слонов' },
      { name: 'Форт Галле', emoji: '🏰', city: 'Галле', desc: 'Голландский форт XVI века, ЮНЕСКО' },
    ],
    photos: [
      { label: 'Сигирия', color: '#E74C3C', icon: '🏛' },
      { label: 'Чайные холмы', color: '#27AE60', icon: '🍵' },
      { label: 'Пляжи', color: '#2980B9', icon: '🏖' },
    ],
    tours: [
      { name: 'Шри-Ланка 10 ночей', meta: 'Перелёт + Heritance Kandalama 5★', price: 235000, nights: 10 },
      { name: 'Культурный тур', meta: 'Коломбо+Канди+Сигирия+Галле', price: 278000, nights: 9 },
      { name: 'Пляжный отдых', meta: 'Anantara Peace Haven 5★', price: 385000, nights: 7 },
    ]
  },

  usa: {
    name: 'США',
    flag: '🇺🇸',
    capital: 'Вашингтон',
    currency: 'Доллар США ($)',
    language: 'Английский',
    timezone: 'UTC-5 до UTC-10',
    climate: 'Разнообразный: от тропического до арктического',
    visa: 'required',
    visaText: 'Требуется туристическая виза B1/B2',
    bestTime: 'Апрель–Июнь, Сентябрь–Октябрь',
    heroGradient: 'linear-gradient(135deg, #2C3E50 0%, #3498DB 100%)',
    description: 'США — страна безграничных возможностей. Нью-Йорк, Лас-Вегас, Гранд-Каньон, Голливуд, Майами — каждый штат как отдельная страна.',
    attractions: [
      { name: 'Статуя Свободы', emoji: '🗽', city: 'Нью-Йорк', desc: 'Символ свободы и Америки' },
      { name: 'Таймс-сквер', emoji: '🏙', city: 'Нью-Йорк', desc: 'Сердце Манхэттена, неоновые огни' },
      { name: 'Гранд-Каньон', emoji: '🏜', city: 'Аризона', desc: 'Одно из чудес природы, 1.6 км глубины' },
      { name: 'Лас-Вегас', emoji: '🎰', city: 'Невада', desc: 'Город развлечений в пустыне' },
      { name: 'Голливуд', emoji: '🎬', city: 'Лос-Анджелес', desc: 'Мировая столица кинематографа' },
      { name: 'Майами-Бич', emoji: '🏖', city: 'Майами', desc: 'Art Deco, белый песок и вечеринки' },
    ],
    photos: [
      { label: 'Нью-Йорк', color: '#2C3E50', icon: '🗽' },
      { label: 'Лас-Вегас', color: '#E74C3C', icon: '🎰' },
      { label: 'Гранд-Каньон', color: '#E67E22', icon: '🏜' },
    ],
    tours: [
      { name: 'Нью-Йорк 7 ночей', meta: 'Перелёт + The Plaza Hotel 5★', price: 580000, nights: 7 },
      { name: 'Калифорния', meta: 'Лос-Анджелес+Сан-Франциско, отели 4★', price: 645000, nights: 10 },
      { name: 'Восточное побережье', meta: 'Нью-Йорк+Вашингтон+Майами', price: 720000, nights: 12 },
    ]
  },

  mexico: {
    name: 'Мексика',
    flag: '🇲🇽',
    capital: 'Мехико',
    currency: 'Мексиканское песо (MXN)',
    language: 'Испанский',
    timezone: 'UTC-6',
    climate: 'Тропический / Субтропический',
    visa: 'free',
    visaText: 'Безвизовый въезд до 180 дней',
    bestTime: 'Ноябрь–Апрель',
    heroGradient: 'linear-gradient(135deg, #27AE60 0%, #C0392B 100%)',
    description: 'Мексика — страна древних цивилизаций, текилы и карибских пляжей. Канкун, Чичен-Ица, Мехико — здесь майя встречается с современностью.',
    attractions: [
      { name: 'Чичен-Ица', emoji: '🏛', city: 'Юкатан', desc: 'Пирамида Кукулькана, чудо света' },
      { name: 'Канкун', emoji: '🏖', city: 'Кинтана-Роо', desc: 'Карибские пляжи и коралловые рифы' },
      { name: 'Мехико', emoji: '🏙', city: 'Мехико', desc: 'Один из крупнейших городов мира' },
      { name: 'Тулум', emoji: '🏝', city: 'Кинтана-Роо', desc: 'Руины майя на обрыве над морем' },
      { name: 'Плайя-дель-Кармен', emoji: '🌴', city: 'Кинтана-Роо', desc: 'Курорт на Ривьера-Майя' },
      { name: 'Сеноты', emoji: '💧', city: 'Юкатан', desc: 'Подземные озёра для купания' },
    ],
    photos: [
      { label: 'Канкун', color: '#2980B9', icon: '🏖' },
      { label: 'Чичен-Ица', color: '#E67E22', icon: '🏛' },
      { label: 'Тулум', color: '#27AE60', icon: '🏝' },
    ],
    tours: [
      { name: 'Канкун 7 ночей', meta: 'Перелёт + Hyatt Ziva 5★ all-inclusive', price: 385000, nights: 7 },
      { name: 'Ривьера-Майя', meta: 'Grand Velas 5★, экскурсии включены', price: 480000, nights: 10 },
      { name: 'Мексика Grand Tour', meta: 'Мехико+Оахака+Канкун, отели 4★', price: 545000, nights: 12 },
    ]
  },

  australia: {
    name: 'Австралия',
    flag: '🇦🇺',
    capital: 'Канберра',
    currency: 'Австралийский доллар (AUD)',
    language: 'Английский',
    timezone: 'UTC+10',
    climate: 'Разнообразный: тропический, умеренный',
    visa: 'required',
    visaText: 'Требуется электронная виза (ETA)',
    bestTime: 'Сентябрь–Ноябрь, Март–Май',
    heroGradient: 'linear-gradient(135deg, #2980B9 0%, #F39C12 100%)',
    description: 'Австралия — континент-страна с уникальной природой. Сиднейская опера, Большой Барьерный Риф, красный Улуру и коалы — здесь всё не как везде.',
    attractions: [
      { name: 'Сиднейская опера', emoji: '🎭', city: 'Сидней', desc: 'Архитектурный шедевр XX века' },
      { name: 'Большой Барьерный Риф', emoji: '🤿', city: 'Квинсленд', desc: 'Крупнейшая коралловая система мира' },
      { name: 'Улуру', emoji: '🏜', city: 'Северная территория', desc: 'Священная красная скала аборигенов' },
      { name: 'Мост Харбор-Бридж', emoji: '🌉', city: 'Сидней', desc: 'Подъём на вершину — лучший вид' },
      { name: 'Мельбурн', emoji: '☕', city: 'Мельбурн', desc: 'Культурная столица, кофейная мекка' },
      { name: 'Голд-Кост', emoji: '🏖', city: 'Квинсленд', desc: '70 км золотых пляжей и сёрфинга' },
    ],
    photos: [
      { label: 'Сидней', color: '#2980B9', icon: '🎭' },
      { label: 'Барьерный Риф', color: '#00B4DB', icon: '🤿' },
      { label: 'Улуру', color: '#E74C3C', icon: '🏜' },
    ],
    tours: [
      { name: 'Сидней 7 ночей', meta: 'Перелёт + Park Hyatt Sydney 5★', price: 620000, nights: 7 },
      { name: 'Восточное побережье', meta: 'Сидней+Кэрнс+Мельбурн, отели 4★', price: 780000, nights: 12 },
      { name: 'Барьерный Риф', meta: 'Кэрнс, Qualia Resort 5★, дайвинг', price: 890000, nights: 8 },
    ]
  }
};
