import { createContext, useContext, useState } from 'react'

const translations = {
  ru: {
    'nav-services': 'Услуги', 'nav-destinations': 'Направления',
    'nav-booking': 'Бронирование', 'nav-contacts': 'Контакты',
    'nav-dashboard': 'Мои поездки', 'nav-login': 'Войти', 'nav-register': 'Регистрация',
    'nav-logout': 'Выйти',
    'btn-book': 'Забронировать',
    'hero-badge': 'Путешествие без границ',
    'hero-title-1': 'Ваше путешествие',
    'hero-title-2': 'никогда не кончается',
    'hero-subtitle': 'От железнодорожных вокзалов до океанских портов и аэропортов — мы соединяем каждое направление на Земле в один бесшовный маршрут.',
    'btn-explore': 'Изучить направления', 'btn-learn': 'Узнать больше',
    'stat-countries': 'Стран', 'stat-routes': 'Маршрутов', 'stat-travelers': 'Путешественников',
    'services-tag': 'Наши услуги', 'services-title-1': 'Любой маршрут —', 'services-title-2': 'одно место',
    'services-subtitle': 'Три вида путешествий под любые желания и бюджет',
    'service-train': 'Железная дорога', 'service-cruise': 'Круизы', 'service-air': 'Авиаперелёты',
    'service-train-desc': 'Межгородские и международные маршруты. Купе, панорамные вагоны, скоростные поезда.',
    'service-cruise-desc': 'Морские путешествия на роскошных лайнерах. Средиземноморье, Карибы, Фьорды.',
    'service-air-desc': 'Рейсы по всему миру. Бизнес-класс, эконом, стыковочные рейсы.',
    'service-link': 'Выбрать маршрут →', 'badge-popular': 'Популярное',
    'dest-tag': 'Направления', 'dest-title-1': 'Популярные', 'dest-title-2': 'маршруты',
    'dest-subtitle': 'Самые популярные направления среди наших путешественников',
    'from-text': 'от',
    'booking-tag': 'Бронирование', 'booking-title-1': 'Найдите', 'booking-title-2': 'свой маршрут',
    'booking-subtitle': 'Поиск по лучшим ценам среди 3200+ маршрутов',
    'tab-train': 'Поезд', 'tab-cruise': 'Круиз', 'tab-air': 'Авиа',
    'field-from': 'Откуда', 'field-to': 'Куда', 'field-depart': 'Отправление',
    'field-return': 'Возврат', 'field-passengers': 'Пассажиры',
    'btn-search': '🔍 Найти маршруты', 'btn-book-now': 'Забронировать',
    'reviews-tag': 'Отзывы', 'reviews-title-1': 'Что говорят', 'reviews-title-2': 'наши клиенты',
    'faq-tag': 'Вопросы и ответы', 'faq-title-1': 'Часто задаваемые', 'faq-title-2': 'вопросы',
    'contacts-tag': 'Контакты', 'contacts-title-1': 'Свяжитесь', 'contacts-title-2': 'с нами',
    'contacts-subtitle': 'Мы ответим в течение 2 часов в рабочее время',
    'c-name': 'Ваше имя', 'c-message': 'Сообщение', 'btn-send': 'Отправить сообщение',
    'footer-rights': 'Все права защищены.',
    'weather-label': 'Погода сейчас',
    'login-title': 'Войти в аккаунт', 'register-title': 'Создать аккаунт',
    'dashboard-title': 'Мои бронирования', 'no-bookings': 'У вас пока нет бронирований',
  },
  en: {
    'nav-services': 'Services', 'nav-destinations': 'Destinations',
    'nav-booking': 'Booking', 'nav-contacts': 'Contacts',
    'nav-dashboard': 'My Trips', 'nav-login': 'Login', 'nav-register': 'Sign Up',
    'nav-logout': 'Logout',
    'btn-book': 'Book Now',
    'hero-badge': 'Travel Without Limits',
    'hero-title-1': 'Your Journey',
    'hero-title-2': 'Never Ends',
    'hero-subtitle': 'From railway stations to ocean ports to airports — we connect every destination on Earth into one seamless experience.',
    'btn-explore': 'Explore Destinations', 'btn-learn': 'Learn More',
    'stat-countries': 'Countries', 'stat-routes': 'Routes', 'stat-travelers': 'Travelers',
    'services-tag': 'Our Services', 'services-title-1': 'Any Route —', 'services-title-2': 'One Place',
    'services-subtitle': 'Three types of travel for any taste and budget',
    'service-train': 'Railways', 'service-cruise': 'Cruises', 'service-air': 'Flights',
    'service-train-desc': 'Intercity and international routes. Cabins, panoramic cars, high-speed trains.',
    'service-cruise-desc': 'Sea voyages on luxury liners. Mediterranean, Caribbean, Norwegian Fjords.',
    'service-air-desc': 'Flights worldwide. Business class, economy, connecting flights.',
    'service-link': 'Choose Route →', 'badge-popular': 'Popular',
    'dest-tag': 'Destinations', 'dest-title-1': 'Popular', 'dest-title-2': 'Routes',
    'dest-subtitle': 'The most requested destinations among our travelers',
    'from-text': 'from',
    'booking-tag': 'Booking', 'booking-title-1': 'Find', 'booking-title-2': 'Your Route',
    'booking-subtitle': 'Search the best prices across 3200+ routes',
    'tab-train': 'Train', 'tab-cruise': 'Cruise', 'tab-air': 'Flight',
    'field-from': 'From', 'field-to': 'To', 'field-depart': 'Departure',
    'field-return': 'Return', 'field-passengers': 'Passengers',
    'btn-search': '🔍 Search Routes', 'btn-book-now': 'Book Now',
    'reviews-tag': 'Reviews', 'reviews-title-1': 'What our', 'reviews-title-2': 'clients say',
    'faq-tag': 'FAQ', 'faq-title-1': 'Frequently Asked', 'faq-title-2': 'Questions',
    'contacts-tag': 'Contact', 'contacts-title-1': 'Get In', 'contacts-title-2': 'Touch',
    'contacts-subtitle': 'We respond within 2 hours during business hours',
    'c-name': 'Your Name', 'c-message': 'Message', 'btn-send': 'Send Message',
    'footer-rights': 'All rights reserved.',
    'weather-label': 'Current weather',
    'login-title': 'Login', 'register-title': 'Create Account',
    'dashboard-title': 'My Bookings', 'no-bookings': 'You have no bookings yet',
  },
  de: {
    'nav-services': 'Leistungen', 'nav-destinations': 'Reiseziele',
    'nav-booking': 'Buchung', 'nav-contacts': 'Kontakt',
    'nav-dashboard': 'Meine Reisen', 'nav-login': 'Anmelden', 'nav-register': 'Registrieren',
    'nav-logout': 'Abmelden',
    'btn-book': 'Jetzt buchen',
    'hero-badge': 'Reisen ohne Grenzen',
    'hero-title-1': 'Deine Reise',
    'hero-title-2': 'hört nie auf',
    'hero-subtitle': 'Von Bahnhöfen über Häfen bis zu Flughäfen — wir verbinden jeden Ort der Erde zu einem nahtlosen Erlebnis.',
    'btn-explore': 'Reiseziele entdecken', 'btn-learn': 'Mehr erfahren',
    'stat-countries': 'Länder', 'stat-routes': 'Routen', 'stat-travelers': 'Reisende',
    'services-tag': 'Unsere Leistungen', 'services-title-1': 'Jede Route —', 'services-title-2': 'ein Ort',
    'services-subtitle': 'Drei Reisearten für jeden Geschmack und jedes Budget',
    'service-train': 'Zugfahrten', 'service-cruise': 'Kreuzfahrten', 'service-air': 'Flüge',
    'service-train-desc': 'Interregionale und internationale Strecken. Kabinen, Panoramawagen, Schnellzüge.',
    'service-cruise-desc': 'Seereisen auf Luxusliner. Mittelmeer, Karibik, Norwegische Fjorde.',
    'service-air-desc': 'Flüge weltweit. Business Class, Economy, Anschlussflüge.',
    'service-link': 'Route wählen →', 'badge-popular': 'Beliebt',
    'dest-tag': 'Reiseziele', 'dest-title-1': 'Beliebte', 'dest-title-2': 'Routen',
    'dest-subtitle': 'Die beliebtesten Reiseziele unserer Kunden',
    'from-text': 'ab',
    'booking-tag': 'Buchung', 'booking-title-1': 'Finde', 'booking-title-2': 'deine Route',
    'booking-subtitle': 'Suche zum Bestpreis unter 3200+ Routen',
    'tab-train': 'Zug', 'tab-cruise': 'Kreuzfahrt', 'tab-air': 'Flug',
    'field-from': 'Von', 'field-to': 'Nach', 'field-depart': 'Abfahrt',
    'field-return': 'Rückreise', 'field-passengers': 'Passagiere',
    'btn-search': '🔍 Routen suchen', 'btn-book-now': 'Jetzt buchen',
    'reviews-tag': 'Bewertungen', 'reviews-title-1': 'Was unsere', 'reviews-title-2': 'Kunden sagen',
    'faq-tag': 'FAQ', 'faq-title-1': 'Häufig gestellte', 'faq-title-2': 'Fragen',
    'contacts-tag': 'Kontakt', 'contacts-title-1': 'Kontaktiere', 'contacts-title-2': 'uns',
    'contacts-subtitle': 'Wir antworten innerhalb von 2 Stunden während der Geschäftszeiten',
    'c-name': 'Dein Name', 'c-message': 'Nachricht', 'btn-send': 'Nachricht senden',
    'footer-rights': 'Alle Rechte vorbehalten.',
    'weather-label': 'Aktuelles Wetter',
    'login-title': 'Anmelden', 'register-title': 'Konto erstellen',
    'dashboard-title': 'Meine Buchungen', 'no-bookings': 'Noch keine Buchungen vorhanden',
  }
}

const LangContext = createContext()

export function LangProvider({ children }) {
  const [lang, setLang] = useState('ru')
  const t = (key) => translations[lang][key] || key
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
